fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
end

platform :android do
  # Android Lanes
end

desc 'Fetch certificates and provisioning profiles'
lane :certificates do
  match(app_identifier: 'com.app.varun', type: 'development', readonly: true)
  match(app_identifier: 'com.app.varun', type: 'appstore', readonly: true)
end